#!/usr/bin/env python3

import argparse
import math


def main(args):
    n = args.value
    nbits = int(math.ceil(math.log2(n)))
    if nbits > 16 * 1024:
        raise ValueError(
            "Whoah there cowboy - sure you wanna do more than 16 kibibits? Comment me out if you do."
        )
    nbits_ndigits_b10 = int(math.ceil(math.log10(nbits)))
    nbytes = int(math.ceil(nbits / 8))
    nnibbles = nbytes * 2
    i = 0
    while n != 0:
        if n & 1:
            b = 1 << i
            print(f"bit {i:{nbits_ndigits_b10}} <=> {b:#0{nnibbles + 2}x}")
        n >>= 1
        i += 1


if __name__ == "__main__":
    parser = argparse.ArgumentParser("whatbits")
    parser.add_argument(
        "value", type=lambda o: int(o, 0), metavar="VAL", help="Value (int(val, 0) parsing)"
    )
    args = parser.parse_args()
    main(args)
