#!/usr/bin/env python3

import argparse
import subprocess

def main(args):
    ycmds = [
        f"read_verilog {args.in_file}",
        "proc",
        "opt_clean",
        "opt",
        # "proc_clean",
        # "opt_clean",
        # "opt",
        f"write_verilog {args.out_file}",
    ]
    yargs = []
    for ycmd in ycmds:
        yargs.append("-p")
        yargs.append(ycmd)
    subprocess.check_call(["yosys", *yargs])

if __name__ == "__main__":
    parser = argparse.ArgumentParser("yosys-opt")
    parser.add_argument("in_file", metavar="in", help="Input verilog file")
    parser.add_argument("out_file", metavar="out", help="Output optimized verilog file")
    args = parser.parse_args()
    main(args)
